### PR TITLE
Handle Windows  filenames in cider-compilation-regex

### PR DESCRIPTION
**Pull request by juergenhoetzel**

### CODE REVIEW

**Comment by bbatsov** [comment]
The change looks OK to me. I'd change the second commit message to `Match windows file names in cider-compilation-regexp`. It'd be nice to mention this in the changelog as well.

**Comment by juergenhoetzel** [comment]
That makes sense: I amended the commit.

**Comment by bbatsov** [comment]
I still don't see a changelog entry.

**Comment by juergenhoetzel** [comment]
:disappointed: Sorry missed out changelog entry in previous commit: Amended again.

**Comment by bbatsov** [comment]
:+1:

**Pull request merged**
