### PR TITLE
More bug fixes from master for the 0.10.1 release

### PR DESCRIPTION
**Pull request by cap10morgan**
I'll start running this locally to see if I encounter any issues.

### CODE REVIEW

**Comment by bbatsov** [comment]
I'll keep this PR open for now, so we can add a bit more commits to it until the end of the week. Let's aim for a release of 0.10.1 early next week. I doubt that many people are at work between Christmas and New Year's Eve anyway, so the release is not super urgent.

**Comment by cap10morgan** [comment]
@bbatsov Sounds good. I'll keep pushing fixes until then.

**Comment by bbatsov** [comment]
Great!

**Comment by bbatsov** [comment]
We're good for a `clojure-mode` 5.1 release tomorrow and we'll probably do the cider 0.10.1 release then as well.

**Comment by bbatsov** [comment]
We'll also have to pull in the `cider-nrepl` part of 942203e.

**Comment by bbatsov** [comment]
This should also be part of 0.10.1 https://github.com/clojure-emacs/cider/pull/1500

**Comment by cap10morgan** [comment]
@bbatsov Release schedule sounds good. Anything else I should bring in?

What's your usual testing process for a release? I'm going to fire this code up locally and kick it around a bit, but would be happy to apply a more comprehensive process if you have one.

**Comment by bbatsov** [comment]
Just do a bit of manual testing of the fixes we brought in. The process is quite simple - I tag and push. :-)

**Comment by bbatsov** [comment]
`clojure-mode` 5.1 is out!

**Comment by cap10morgan** [comment]
@bbatsov I pushed that other commit you mentioned to cider-nrepl, but I haven't had a chance to test everything yet.

**Comment by bbatsov** [comment]
OK, let me know when get to doing this.

We'll probably add https://github.com/clojure-emacs/cider/pull/1502 to 0.10.1 as well.

**Comment by cap10morgan** [comment]
@bbatsov I don't personally use paredit (smartparens instead), so it might be good if someone else tested #1479.

**Comment by cap10morgan** [comment]
OK, all but #1479 and #1435 are tested and seem to be working in this branch.

**Comment by cap10morgan** [comment]
#1435 looks good.

**Comment by cap10morgan** [comment]
Actually, I think #1435 is *not* fixed in this branch. It's still broken in this screenshot, no?

screen shot 2016-01-04 at 3 35 40 pm

**Comment by cap10morgan** [comment]
Should we fix https://github.com/clojure-emacs/cider/issues/1503 before releasing v0.10.1?

**Comment by jeffvalk** [comment]
@cap10morgan #1486 is fixed in the screenshots above, yes.

**Comment by cap10morgan** [comment]
Pulling in https://github.com/cap10morgan/cider/commit/0f0bb06b87d1d743e339c7c13ff5a7ddf0189d53 fixed #1503.

I think the only thing left is to have a paredit user test #1479 and then we should be good to go.

**Comment by bbatsov** [comment]
> I think the only thing left is to have a paredit user test #1479 and then we should be good to go.

That's working. :-)

**Comment by bbatsov** [comment]
I cut a new release, but it's probably broken due to an error in the middleware. The last commit backported there breaks the tests, but I noticed this too late and I didn't really have to investigate. I won't announce the release until we see what's wrong and I'll just swap the middleware jar.

**Pull request merged**
