### PR TITLE
middleware_setup.adoc: add instructions for refactor-nrepl

### PR DESCRIPTION
**Pull request by vemv**
* Upgrade refactor-nrepl references in tests
* middleware_setup.adoc: add instructions for refactor-nrepl

...I don't feel too strongly about this one, but seems a sensible improvement (aligned with https://docs.cider.mx/cider/cljs/shadow-cljs.html which also suggests refactor-nrepl).

Cheers - V

### CODE REVIEW

**Comment by bbatsov** [comment]
Hmmm, I'll have to think about this. I've intentionally avoided refactor-nrepl in most of the docs, just because so many issues historically came from people trying clj-refactor.el without them knowing what they're are doing. Given that people are often new to both Emacs and Clojure a more complex setup is a recipe for issues IMO.

**Comment by vemv** [comment]
That's reasonable.

Maybe I can include the code preceded by `#_`?

**Comment by bbatsov** [comment]
I think it's best to just keep this out of CIDER's docs.

**Comment by vemv** [comment]
No issue!

**Pull request closed without merging**
