### PR TITLE
Debugger menu and configurable input prompt

### PR DESCRIPTION
**Pull request by Malabarba**
- The menu is pretty straightforward.
- The configurable input prompt (the list of debug keys) can be shown on the minibuffer, on an overlay above the function, on both, or not at all. I think I'll make `overlay` the default, so the echo-area will be less crowded. When the top of the function is not visible, the top of the window is used instead.

What do you say?

### CODE REVIEW

**Comment by bbatsov** [comment]
I say "Aye!".

**Comment by bbatsov** [comment]
Hmm, something's wrong with Travis.

**Comment by Malabarba** [comment]
At least it got to the compiling stage. I've got a package where half the time I can't get travis to clone the repo. 

Did you try restarting the build?

**Comment by bbatsov** [comment]
Yep, I restarted it.

**Comment by Malabarba** [comment]
Ah ok. I was reading it on my phone yesterday, and it looked like the build was stopping at the compile stage. But I see now it's just a normal tests thing. I'll get to it.

**Comment by Malabarba** [comment]
Ok. it's passing now.

**Comment by Malabarba** [comment]
Hold on, don't merge yet. After playing around on my work PC I realise I don't like the way this looks. I'll have to fine tune it a bit more.

**Comment by Malabarba** [comment]
Ok, it works nicer now I think.
The previous version would remove the overlays immediately after the user sent a command, and recreate them when a new input-request was received. This caused a noticeable flicker on all the overlays, because Emacs actually has time to do a redisplay in between those two events.

The current version doesn't immediately remove the overlays, instead it removes them when the next input request is received or after a fraction of a second (whichever comes first). In my system, this is enough to avoid the flicker.

**Comment by bbatsov** [comment]
:+1:

**Pull request merged**
