### PR TITLE
Tweaks to cider browse ns

### PR DESCRIPTION
**Pull request by expez**
I'll squash the two commits changing the bindings into one, if you agree, and reference https://github.com/clojure-emacs/cider/issues/1066

### CODE REVIEW

**Comment by bbatsov** [comment]
While on the topic of `browse-ns` changes - I was about to rename it to `cider-ns-browser`. You might do this as well.

I'm also not fond of commit titles prefixed with file names, so please update those.

**Comment by bbatsov** [comment]
@expez ping

**Comment by expez** [comment]
I'll leave the renaming for later

**Comment by bbatsov** [comment]
The first commit message is starting with a lowercase letter.

**Comment by bbatsov** [comment]
:+1: Thanks!

**Pull request merged**
