### PR TITLE
Dynamically upgrade nrepl connection

### PR DESCRIPTION
**Pull request by plexus**
Piece together the final pieces to make dynamic loading + sideloading of
middleware work.

This introduces `M-x cider-upgrade-nrepl-connection`, which combines the different steps needed
- fetch the cider-nrepl jar
- start the sideloader
- insert the middleware
- reload the nREPL capabilities

This introduces a cider-jar mini library for looking up jars and files in jars fairly efficiently and in a cross-platform manner.

Part of https://github.com/clojure-emacs/cider/issues/3037

-----------------

Before submitting the PR make sure the following things have been done (and denote this
by checking the relevant checkboxes):

- [x] The commits are consistent with our [contribution guidelines](../blob/master/.github/CONTRIBUTING.md)
- [-] You've added tests (if possible) to cover your change(s)
- [x] All tests are passing (`eldev test`)
- [x] All code passes the linter (`eldev lint`) which is based on [`elisp-lint`](https://github.com/gonewest818/elisp-lint) and includes
  - [byte-compilation](https://www.gnu.org/software/emacs/manual/html_node/elisp/Byte-Compilation.html), [`checkdoc`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Tips.html), [check-declare](https://www.gnu.org/software/emacs/manual/html_node/elisp/Declaring-Functions.html), packaging metadata, indentation, and trailing whitespace checks.
- [x] You've updated the [changelog](../blob/master/CHANGELOG.md) (if adding/changing user-visible functionality)
- [ ] You've updated the [user manual](../blob/master/doc) (if adding/changing user-visible functionality)

Thanks!

*If you're just starting out to hack on CIDER you might find this [section of its
manual][1] extremely useful.*

[1]: https://docs.cider.mx/cider/contributing/hacking.html

### CODE REVIEW

**Comment by plexus** [comment]
Apparently `string-replace` is an Emacs 28 thing.

**Comment by plexus** [comment]
And it seems relying on internals of `arc-mode` wasn't smart either :sweat_smile:

**Comment by plexus** [comment]
Good thing we test on Emacs 25/26/27, and I use 28. Seems in 28 the implementation of arc-mode was changed to use structs instead of vectors. Will look into the remaining failures tomorrow.

**Comment by plexus** [comment]
God I hate linters.

**Comment by plexus** [comment]
I give up...

``` emacs-lisp
     (if (functionp #'archive--file-desc-ext-file-name)
         #'archive--file-desc-ext-file-name
```

eldev lint is complaining about this, because it's not defined. Which is correct, it's defined on Emacs 28, which is why it's there. meanwhile I can only find out through CI because locally eldev lint gives me completely different results, and it seems there's no way to give it a hint to ignore this.

**Comment by plexus** [comment]
Linter passed... IMO the code has gotten worse in the process but the machines are happy.

**Comment by plexus** [comment]
That... actually worked :D CI is looking ok now, apart from the invisible windows builds.

**Comment by bbatsov** [comment]
Great work! 🚀

**Pull request merged**
