### PR TITLE
Fix shell quoting in Gradle tests

### PR DESCRIPTION
**Pull request by ajoberstar**
Needed to pass Windows

-----------------

Before submitting the PR make sure the following things have been done (and denote this
by checking the relevant checkboxes):

- [x] The commits are consistent with our [contribution guidelines](../blob/master/.github/CONTRIBUTING.md)
- [x] You've added tests (if possible) to cover your change(s)
- [x] All tests are passing (`eldev test`)
- [x] All code passes the linter (`eldev lint`) which is based on [`elisp-lint`](https://github.com/gonewest818/elisp-lint) and includes
  - [byte-compilation](https://www.gnu.org/software/emacs/manual/html_node/elisp/Byte-Compilation.html), [`checkdoc`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Tips.html), [check-declare](https://www.gnu.org/software/emacs/manual/html_node/elisp/Declaring-Functions.html), packaging metadata, indentation, and trailing whitespace checks.
- [ ] You've updated the [changelog](../blob/master/CHANGELOG.md) (if adding/changing user-visible functionality)
- [ ] You've updated the [user manual](../blob/master/doc) (if adding/changing user-visible functionality)

Thanks!

*If you're just starting out to hack on CIDER you might find this [section of its
manual][1] extremely useful.*

[1]: https://docs.cider.mx/cider/contributing/hacking.html

### CODE REVIEW

**Comment by ajoberstar** [comment]
@vemv This should fix those failing Windows tests

**Comment by vemv** [comment]
Indeed, it's green now!

@bbatsov , you might want to create a CIDER release

**Comment by bbatsov** [comment]
@vemv Let's do it after @ajoberstar does all the Gradle changes he has in mind.

**Comment by vemv** [comment]
They're done! https://github.com/clojure-emacs/cider/pull/3228#issuecomment-1200340807

**Pull request merged**
