### PR TITLE
Modify cider-boot-parameters to match the new boot task

### PR DESCRIPTION
**Pull request by arichiardi**
This follows changes in `cider-nrepl` introducing the new `nrepl-server` boot
task.

-----------------

Before submitting the PR make sure the following things have been done (and denote this
by checking the relevant checkboxes):

- [X] The commits are consistent with our [contribution guidelines](../blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by arichiardi** [comment]
I have tested this with a Clojure file and no problem. There is still a problem with the cljs REPL, which is probably going to need a change in `boot-cljs-repl`.

**Comment by bbatsov** [comment]
Nice! 

> I have tested this with a Clojure file and no problem. There is still a problem with the cljs REPL, which is probably going to need a change in boot-cljs-repl.

@arichiardi I guess you'll take care of those, right? What are those problems, btw?

**Comment by arichiardi** [comment]
A couple of deps are outdated, see https://github.com/adzerk-oss/boot-cljs-repl/issues/60.

About taking care of those, it is very low in my priority atm because I have switched to `shadow-cljs` and `figwheel-main`. I will definitely be able to help there though or do it myself at some point.

The only thing I am afraid of is that I am not very familiar with the changes to piggieback, so probably I need to spend some time for learning things there: `boot-cljs-repl` seems to do something very similar.

**Comment by bbatsov** [comment]
> About taking care of those, it is very low in my priority atm because I have switched to shadow-cljs and figwheel-main. I will definitely be able to help there though or do it myself at some point.

Yeah, I get this. Seems this boot-cljs-repl is not getting any love these days, but I doubt many people are using it. 

> The only thing I am afraid of is that I am not very familiar with the changes to piggieback, so probably I need to spend some time for learning things there: boot-cljs-repl seems to do something very similar.

Isn't it just using piggieback?

**Comment by arichiardi** [comment]
> Isn't it just using piggieback?

https://github.com/adzerk-oss/boot-cljs-repl/blob/master/src/adzerk/boot_cljs_repl.clj#L18-L21

It seems so, so maybe it is an easy one after all, will try smth out before talking nonsense again :smile:

**Comment by bbatsov** [comment]
Oh, it's using Weasel as well... The changes required really are trivial, but if there isn't anyone to merge them, that's a problem...

**Comment by arichiardi** [comment]
So this one can go in now?

**Comment by bbatsov** [comment]
Yeah, we'll merge this soon. The only holdup right now is `refactor-nrepl`, but I'm not that concerned about it.

**Comment by bbatsov** [comment]
Let's get wild! ;-)

**Pull request merged**
