### PR TITLE
[#1719] - Add defcustom for cider-hep-echo

### PR DESCRIPTION
**Pull request by edipofederle**
The title speak for himself

- [x] The commits are consistent with our [contribution guidelines](CONTRIBUTING.md)
- [ ] You've added tests (if possible) to cover your change(s)
- [x] All tests are passing (`make test`)
- [x] The new code is not generating bytecode or `M-x checkdoc` warnings
- [x] You've updated the changelog (if adding/changing user-visible functionality)
- [ ] You've updated the readme (if adding/changing user-visible functionality)
- [ ] You've updated the refcard (if you made changes to the commands listed there)

Thanks!

### CODE REVIEW

**Comment by Malabarba** [comment]
We already have that, it's called `cider-use-tooltips`. ;-)

**Comment by edipofederle** [comment]
Hi @Malabarba,

Oh, now I see. You refer to this: https://github.com/clojure-emacs/cider/blob/master/cider-mode.el#L664 ?

**Comment by Malabarba** [comment]
Yep.

**Comment by edipofederle** [comment]
No problem. Sorry for that :)

**Comment by Malabarba** [comment]
np :+1:

**Pull request closed without merging**
