### PR TITLE
Organize the debug message handler a bit

### PR DESCRIPTION
**Pull request by Malabarba**
This goes with https://github.com/clojure-emacs/cider-nrepl/pull/236

### CODE REVIEW

**Comment by Malabarba** [comment]
Not sure what's goingon, but the test failed with `Invalid function: pushnew`.

**Comment by bbatsov** [comment]
Seems like an issue with cask 0.7.2. //cc @lunaryorn @rejeep 
I'll rollback to 0.7.0.

**Comment by bbatsov** [comment]
Interestingly the same version of Cask is working just fine for Projectile.

**Comment by lunaryorn** [comment]
@bbatsov I don't think that it's Cask's fault. We don't use `pushnew` anywhere.  I rather think that you are lacking a `(require 'cl)` somewhere.

**Comment by bbatsov** [comment]
Yep, you're right. Guess cask 0.7.0 used to require `cl`, but stopped doing so by `0.7.2`. I've just fixed this in cider.

**Comment by rejeep** [comment]
@bbatsov Don't think so, see the diff: https://github.com/cask/cask/compare/v0.7.0...v0.7.2

**Pull request merged**
