### PR TITLE
Add markdown support in the grimmoire buffer

### PR DESCRIPTION
**Pull request by notetiene**
* cider-grimoire.el (cider-create-grimoire-buffer): Activate markdown-mode when
  found.

The `http://conj.io/` gives documentation in the markdown format. I thought it would be nice to get font-lock working. It's a really simple PR.

-----------------

Before submitting the PR make sure the following things have been done (and denote this
by checking the relevant checkboxes):

- [x] The commits are consistent with our [contribution guidelines](https://github.com/clojure-emacs/cider/blob/master/.github/CONTRIBUTING.md)
- [ ] You've added tests (if possible) to cover your change(s)
- [x] All tests are passing (`make test`)
- [x] The new code is not generating bytecode or `M-x checkdoc` warnings
- [ ] You've updated the changelog (if adding/changing user-visible functionality)
- [ ] You've updated the readme (if adding/changing user-visible functionality)
- [ ] You've updated the refcard (if you made changes to the commands listed there)

### CODE REVIEW

**Comment by bbatsov** [comment]
This was discussed and rejected in the past already. `markdown-mode` is for **editing** markdown and what we really need is something that can **render** markdown in Emacs. Such a mode would super useful.

**Comment by bbatsov** [comment]
If this is made optional, and people are interested in it, I might consider merging this change though, as it's pretty simple.

**Comment by xiongtx** [comment]
Don't think there's a good solution to rendering in Emacs; maybe when WebKit support is built-in?

We *could* [use `eww` to render](https://www.reddit.com/r/emacs/comments/2x4jtt/render_markdown_in_a_buffer/cowyg9e/):

```emacs-lisp
(defun gk-markdown-preview-buffer ()
  (interactive)
  (let* ((buf-this (buffer-name (current-buffer)))
         (buf-html (get-buffer-create
                    (format "*gk-md-html (%s)*" buf-this))))
    (markdown-other-window (buffer-name buf-html))
    (shr-render-buffer buf-html)
    (eww-mode)
    (kill-buffer buf-html)))
```

But the results aren't that different:

Markdown           |  `eww`
:-------------------------:|:-------------------------:
Markdown  |  eww

**Comment by bbatsov** [comment]
@xiongtx I actually like this solution! Let's go with it. I still it still relies on `markdown-mode` so there should probably be some conditional check and its absense we should fallback to the current code.

**Comment by xiongtx** [comment]
I'm not a big fan of this solution. 

If you look at the `eww` rendering, the arities under `Usages` are all joined onto one line. This could be considered a Grimoire problem, but is ugly either way.

**Comment by bbatsov** [comment]
Ah, yeah - it looks pretty different here https://www.conj.io/store/v1/org.clojure/clojure/1.8.0/clj/clojure.core/vector

Guess there's not much we can do then.

**Comment by xiongtx** [comment]
I think the biggest value-add would be font-locking for the Clojure code, not for the MD titles and such. What do you think?

**Comment by bbatsov** [comment]
I agree.

**Pull request closed without merging**
