### PR TITLE
clojure-cli: provide a mechanism to configure default aliases

### PR DESCRIPTION
**Pull request by pyr**
The clojure CLI does not impose any convention on what the default
alias for a project should be. It is also common practice to
only have the necessary environment for production in the
root dependency expressions.

As a result, jacking in without modification often results in
a REPL environment that is too constrained.

This patch looks up the current `deps.edn` file to look for a
`:cider/default-aliases` key, when that key is present and
contains a collection, it is processed to produce the correct
alias stanza for the clojure CLI commandline.

- [X] Commits are consistent with our [contribution guidelines](../blob/master/.github/CONTRIBUTING.md)
- [X] You've added tests (if possible) to cover your change(s)
- [ ] All tests are passing (`eldev test`)
- [x] All code passes the linter (`eldev lint`) which is based on [`elisp-lint`](https://github.com/gonewest818/elisp-lint) and includes
  - [byte-compilation](https://www.gnu.org/software/emacs/manual/html_node/elisp/Byte-Compilation.html), [`checkdoc`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Tips.html), [check-declare](https://www.gnu.org/software/emacs/manual/html_node/elisp/Declaring-Functions.html), packaging metadata, indentation, and trailing whitespace checks.
- [ ] You've updated the [changelog](../blob/master/CHANGELOG.md) (if adding/changing user-visible functionality)
- [ ] You've updated the [user manual](../blob/master/doc) (if adding/changing user-visible functionality)

### CODE REVIEW

**Comment by pyr** [comment]
I am in the process of figuring out how to run tests since my file-mocking macro does not seem to make eldev happy for now. Before going further I wanted a bit of feedback on the idea and whether it was worth following up on it.

**Comment by plexus** [comment]
For what it's worth, we've been using `.dir-locals.el` for this for a long time, works like a charm. This has the benefit that you can set up other project-specific config, e.g. we sometimes have a non-standard cljs-repl setup.

E.g.

```lisp
((nil . ((cider-clojure-cli-global-options . "-A:dev:test"))))
```

or

```lisp
((nil . ((cider-clojure-cli-global-options     . "-A:dev:test")
         (cider-custom-cljs-repl-init-form     . "(user/shadow-cljs-repl)")
         (cider-default-cljs-repl              . custom)
         (cider-preferred-build-tool           . clojure-cli)
         (eval . (progn
                   (make-variable-buffer-local 'cider-jack-in-nrepl-middlewares)
                   (add-to-list 'cider-jack-in-nrepl-middlewares "shadow.cljs.devtools.server.nrepl/middleware"))))))
```

**Comment by pyr** [comment]
Hi @plexus, thinking about it, your approach is probably the best, I'll go with that, thanks!
Something like my patch would only make sense if most tooling agreed to honor it, and then `:cider/` would be the wrong namespace, I'll drop it.

Cheers

**Comment by vemv** [comment]
btw, if you think the doc could be improved somewher in this regard, a suggetion would be much welcome.

I believe people often trip up with clj CLI aliases.

**Comment by bbatsov** [comment]
We can always add something here https://docs.cider.mx/cider/basics/up_and_running.html#customizing-the-jack-in-command-behavior or here https://docs.cider.mx/cider/basics/up_and_running.html#customizing-the-jack-in-command-behavior

Not sure if someone will find it, though. :-)

**Pull request closed without merging**
