### PR TITLE
fix remaining ci errors

### LINKED ISSUE #2133: Print representation of structs in Emacs 26 breaks tests
Some tests are [failing when run against Emacs 26](https://travis-ci.org/clojure-emacs/cider/jobs/314678704#L1868) due to the new `#s` struct print syntax, which seems to be due to the use of [records to represent structs](http://git.savannah.gnu.org/cgit/emacs.git/tree/doc/lispref/records.texi#n27).

### PR DESCRIPTION
**Pull request by gonewest818**
so this is a bit of a grab bag, but it fixes the remaining errors in CI so that builds actually succeed and go green.  Example:  https://travis-ci.org/gonewest818/cider/builds/317882617

changes:
* commits https://github.com/clojure-emacs/cider/commit/bb7c0d6e6c291d22a2caab95c13701f8aeb7d51f and https://github.com/clojure-emacs/cider/commit/9dbe5ee63acdea5a2de1c19187c1ca06fab443bc are needed to fix compiler errors in emacs >=26 where unused arguments cause compiler errors.
* commit https://github.com/clojure-emacs/cider/commit/cafed0ef8377988827ed9398c3d76a8d56ae54b0 fixes #2133, the new print representation for structs in emacs >=26
* commit https://github.com/clojure-emacs/cider/commit/690ddc3aafdcf9b1ee3bbe7f4a0a9af363068b18 fixes incompatibilities with changes to tramp in emacs >=26

### CODE REVIEW

**Comment by gonewest818** [comment]
@xiongtx : looks like we've got some of the same fixes in here!

**Comment by xiongtx** [comment]
:smile: That means we've duplicated knowledge and experience--a valuable rarity in the open-source world!

**Comment by gonewest818** [comment]
Indeed, you did, and most likely better work too, as I'm still relatively new with elisp.

For what it's worth, I set up Travis on my fork so I can experiment freely with fixes and watch the jobs succeed or fail before doing the pull request.

Also, I have a Docker container running based on the Travis base image which gives me a way to run tests locally (and can even bind-mount my working directory so I can keep testing interactively). I'll type that up and check that in, if anyone's interested.

**Comment by xiongtx** [comment]
>  I'll type that up and check that in, if anyone's interested.

Definitely sounds interesting! I've been trying to figure out the best way to test against multiple Emacs versions locally, but I always just end up leaving it to CI 😝.

**Comment by dpsutton** [comment]
@gonewest818 I would love to see how you did the CI and docker stuff as wel

**Comment by bbatsov** [comment]
I was amused to see both of you tackled pretty much the same issues at the same time. 😄  And I appreciate your work very much. I've opted to merged @xiongtx's PRs, as they were submitted first and the one dealing with reported problems was more detailed.

**Comment by gonewest818** [comment]
no problem.  thanks.

**Comment by bbatsov** [comment]
The build is now green for a first time in quite a while! 🎉 🎉 🎉 

Thanks, guys! You're awesome! 🏆

**Comment by timvisher** [comment]
❤️ ❤️ ❤️

**Comment by gonewest818** [comment]
@dpsutton - #2144 will be the issue where I do the docker work if you’re interested.

**Pull request closed without merging**
