### PR TITLE
Use `face` text property for error buffer buttons

### LINKED ISSUE #1033: Erroneous underlining in error buffer
* The filter buttons are always underlined, even when toggled off
* All frames are underlined

e.g. with `font-lock-mode` enabled/disabled:

screenshot 2015-03-20 12 28 01
screenshot 2015-03-20 12 29 03

It seems the default `button` face is always being used as `button` only cares about the `face` property and not the `font-lock-face` property. If I change `cider-stacktrace.el` to use `face` when rendering the buttons and frames, all is better with both `font-lock-mode` enabled and disabled:

screenshot 2015-03-20 12 36 54
screenshot 2015-03-20 12 37 06

Would you accept a PR to this effect? The change to `font-lock-face` was in 401e819, to fix #749 - but I think in this particular case, things like `parenface` and `rainbow-delimiters` don't really apply. Thoughts?

### PR DESCRIPTION
**Pull request by cichli**
Fixes #1033.

### CODE REVIEW

**Comment by vspinu** [comment]
Confirmed. That fixes it. But it's strange as `font-lock-face` is designed to be used in font-lock modes instead of `face`.

**Comment by vspinu** [comment]
Are there other usages of `font-lock-face` also broken or it only concerns buttons?

**Comment by cichli** [comment]
Yeah, I haven't dug in too deeply but this seems to be a `button.el` specific thing. As far as I can tell this is the only place where we're not using the default button face on buttons (we also use buttons in apropos, doc, and test modes, but I'm not seeing this specific issue in any of them).

**Comment by bbatsov** [comment]
:+1: Guess I overdid it when trying to fix the REPL font-locking. :-)

**Pull request merged**
