### PR TITLE
Quick fix for the debugger print-level

### PR DESCRIPTION
**Pull request by Malabarba**
The diff speaks for itself

### CODE REVIEW

**Comment by Malabarba** [comment]
Fixes #1192

**Comment by bbatsov** [comment]
:+1:

**Comment by bbatsov** [comment]
Still, there's an encoding issue as well - `nil` is encoded as `[]` (because it's both `nil` and an empty list in Emacs Lisp and we can't differentiate between the two usages). So, the defaults are definitely not working as expected. I totally missed this earlier today.

**Comment by Malabarba** [comment]
Oooh. I see what you mean. What should I fix this on the nrepl side? Or is there a proper way to pass nil?

**Comment by Malabarba** [comment]
How about #1194?

**Pull request merged**
