### PR TITLE
Add an option to disable automatic cider-mode

### PR DESCRIPTION
**Pull request by abo-abo**
* cider.el (cider-auto-mode): New defcustom.
(cider--connected-handler): Don't auto-enable `cider-mode' for all
`clojure-mode' buffers when `cider-auto-mode' is nil.

### CODE REVIEW

**Comment by bbatsov** [comment]
What's the reasoning here?

**Comment by abo-abo** [comment]
I don't want the extra key bindings and the mode line change. It is a minor mode after all: preferably, it should be opt-in. I ask to at least make it opt-out.

**Comment by bbatsov** [comment]
While this is technically true, CIDER is pretty much unusable without it. The auto-enabling of the mode was borrowed by SLIME. I do have my reservations about it, but I'm also uncertain whether there's a better alternative to the current setup.

**Comment by abo-abo** [comment]
> I do have my reservations about it, but I'm also uncertain whether there's a better alternative to the current setup.

I don't know of a better way either, but CIDER is very usable to me without a minor mode. That's why I propose an opt-out parameter.

**Comment by Malabarba** [comment]
With regards to cider being opt-in, technically, you opt-in when you invoke the `jack-in` or the `connect` command.
Still, I see no reason why we can't have a variable to disable the auto activation of minor modes. Though perhaps a documented defvar might be preferable to a defcustom (so as not to clutter the customization menu).

**Comment by abo-abo** [comment]
> With regards to cider being opt-in, technically, you opt-in when you invoke the jack-in or the connect command.

Not really. What if I just want a REPL? How is `clojure-mode` related to that?  It's a little related, and we have the example of SLIME doing the same thing, but I don't think it's completely the right thing.

I know that this is a recent change, because I haven't seen this behavior before. I bound <kbd>C-l</kbd> to clear the REPL buffer in `cider-mode`.  And I was surprised to find this binding in a `clojure-mode` buffer. I could adjust the key bindings, but the change in mode line is annoying as well.

**Comment by Malabarba** [comment]
> > With regards to cider being opt-in, technically, you opt-in when you invoke the jack-in or the connect command.

> Not really. What if I just want a REPL? How is clojure-mode related to that? It's a little related, and we have the example of SLIME doing the same thing, but I don't think it's completely the right thing.

I'm not saying we shouldn't offer a repl-only option (quite the contrary, think we should). I was just replying to your other comment, that cider isn't opt-in.  
Not being opt-in is when a minor-mode turns itself on as soon as the packge is installed. Cider *is* opt-in, it just doesn't offer (yet) the fine-grained configuration you desire.

**Comment by bbatsov** [comment]
> Not really. What if I just want a REPL? How is clojure-mode related to that? It's a little related, and we have the example of SLIME doing the same thing, but I don't think it's completely the right thing.

Fair point. I was just explaining why it is done as it is now.

> I know that this is a recent change, because I haven't seen this behavior before. I bound C-l to clear the REPL buffer in cider-mode. And I was surprised to find this binding in a clojure-mode buffer. I could adjust the key bindings, but the change in mode line is annoying as well.

This behaviour hasn't been changed since the earliest days of the project. `cider-mode` and `cider-repl-mode` are totally different modes. Not sure what's your problem with the modeline - not knowing the active connection is pretty problematic for everyone using more than one connection. 

I'll think a bit more on how to best tackle this, but you're the first person who has issues with this behaviour for about 3 years now.

**Comment by bbatsov** [comment]
@abo-abo ^^

Btw, you should also mention this change in the changelog.

**Pull request merged**
