### PR TITLE
fix NodeJS CLJS REPL starting

### PR DESCRIPTION
**Pull request by jeffdik**
I get a ClassNotFoundException for cljs.repl.node without this commit.

### CODE REVIEW

**Comment by bbatsov** [comment]
The change seems harmless. I wonder if that's a problem for `rhino` as well. Btw, the commit message has to be capitalised.

**Comment by Malabarba** [comment]
Yes, it's probably best to do it for all of them.

**Comment by jeffdik** [comment]
Ok, I've capitalized the commit message.

I don't have any issues with starting a rhino cljs repl.  It might future-proof this method of starting a cljs repl a bit if cljs.repl.rhino is ever not loaded by default, but I have a slight preference for leaving it as is unless explicitly require'ing becomes necessary.

**Comment by Malabarba** [comment]
One thing I still don't understand is why I sometimes need to require stuff before using and why sometimes I don't.

**Comment by bbatsov** [comment]
No idea. It'd be nice to get some clarity on this.

**Comment by jeffdik** [comment]
In this case, I think cljs.repl.rhino doesn't need to be required because it is already loaded by piggieback: https://github.com/cemerick/piggieback/blob/master/src/cemerick/piggieback.clj#L13

**Comment by bbatsov** [comment]
Good to know. Thanks!

**Pull request merged**
