### PR TITLE
[Issue #1352] Fix checkdoc errors in cider-popup.el

### PR DESCRIPTION
**Pull request by g12l**
It's a simple change but as it is my first PR if I'm not doing things right just let me know !

### CODE REVIEW

**Comment by bbatsov** [comment]
Same thing I said on the other related PR - I did a force-push and you'll have rebase on top of the current `master`. Sorry about this.

**Comment by g12l** [comment]
Ok, I just try to rebase.

**Comment by bbatsov** [comment]
You succeeded! Thanks! :-)

**Comment by g12l** [comment]
That's great to hear, thanks !

**Pull request merged**
