### PR TITLE
Convert version warning to error

### PR DESCRIPTION
**Pull request by Malabarba**
I've had this cause issues to 4 different people already.
Apparently, people don't pay enough attention to warnings. Maybe an error will impose more respect...

### CODE REVIEW

**Comment by bbatsov** [comment]
Maybe this should be a real error, I don't know. Just changing the label is unlikely to improve anything.

**Comment by Malabarba** [comment]
Well, one person did say "I thought that was just a warning." ¬¬
I'm afraid throwing an error might interrupt other code from running and thus cause even more breakage. So maybe a message?

**Comment by bbatsov** [comment]
> Well, one person did say "I thought that was just a warning." ¬¬

Well, technically speaking it's exactly a warning. In some situations there might be no real differences (e.g. shortly after a release) and some people really want to use the basic functionality when connecting to a remote process where the middleware can't be installed.

Perhaps this should be a config setting - an error for version mismatches by default; power users would be able to override this. Not having installed the middleware will result in a (potentially) suppressible warning. Btw, probably it'd be best if we had different messages for missing `cider-nrepl` and a version mismatch.

**Comment by bbatsov** [comment]
Well, it won't hurt to change this for now, but long term I still believe we can improve those startup warnings/errors/whatever.

**Comment by Malabarba** [comment]
Sorry, I completely forgot about this. Been a busy couple of weeks.

**Pull request merged**
