### PR TITLE
Add cider-stacktrace-print-length

### PR DESCRIPTION
**Pull request by cichli**

### CODE REVIEW

**Comment by bbatsov** [comment]
As it stands I'm not sure many people will understand what this does. I know I'm having a hard time understanding it myself and had to consult the middleware change.

**Comment by vspinu** [comment]
How does the *print-length* affect stacktrace more concretely? Will this truncate error lines? A small example would be really helpful. Thanks.

**Comment by cichli** [comment]
Agh, I submitted this earlier than I intended to and apparently only updated the title. What I _meant_ to say was:

This is a more general fix for one potential cause of #1004, in much the same vein of #738 - while we limit printing of very deep data structures, we don't limit printing of long (potentially infinitely so) data structures. For example, evaluating this will cause the error buffer to display but never render anything, and the java process to use 100% of a CPU until killed:

```clojure
(throw (ex-info "" {:a (range)}))
```

Doing the same for a very large range causes the buffer to only render after several seconds. With this fix, anything sequential in the `ex-data` map for each cause will only have its first 50 (by default) elements printed, by binding `clojure.core/*print-length*` when printing the cause data in the middleware [here](https://github.com/clojure-emacs/cider-nrepl/blob/master/src/cider/nrepl/middleware/stacktrace.clj#L129-L131). It's still possible to inspect the cause data in its entirety either at the REPL or in the inspector using `*e`.

It might also be useful to:

* make the printed data foldable separately from the call stack itself (currently you can only fold both at once)
* when initially rendering the error buffer, move the point to the line of first cause itself, rather than the first line in its call stack. If the cause data takes up so many lines that the cause type is off-screen, you currently get no context as to what kind of exception has been thrown (when you're not at the REPL)

@bbatsov I agree that the docstrings aren't perfect. I'll update both this one and `cider-stacktrace-print-level` to be more descriptive and add something to README.md too.

@vspinu this only affects printing of the `ex-data` map above the call stack for each cause that is an instance of `IExceptionInfo`. No actual call stacks, exception messages or exception types are truncated.

**Comment by bbatsov** [comment]
> make the printed data foldable separately from the call stack itself (currently you can only fold both at once)

I agree.

> when initially rendering the error buffer, move the point to the line of first cause itself, rather than the first line in its call stack. If the cause data takes up so many lines that the cause type is off-screen, you currently get no context as to what kind of exception has been thrown (when you're not at the REPL)

Perhaps. Although something like this should definitely be configurable as I imagine not everyone will like it.

> @bbatsov I agree that the docstrings aren't perfect. I'll update both this one and cider-stacktrace-print-level to be more descriptive and add something to README.md too.

Sounds good.

**Comment by cichli** [comment]
I've updated the docstrings for both `cider-stacktrace-print-length` and `cider-stacktrace-print-level`.

**Comment by bbatsov** [comment]
Just squash the related commits together and we're good to go.

**Comment by cichli** [comment]
Done.

**Comment by bbatsov** [comment]
:+1: Thanks!

**Pull request merged**
