### PR TITLE
Add a cider-repl-set-ns-as command

### PR DESCRIPTION
**Pull request by fhalde**
**Allows you to provide an alias for the ns**

-----------------

Before submitting the PR make sure the following things have been done (and denote this
by checking the relevant checkboxes):

- [x] The commits are consistent with our [contribution guidelines](../blob/master/CONTRIBUTING.md)
- [] You've added tests (if possible) to cover your change(s)
- [x] All tests are passing (`make test`)
- [x] All code passes the linter (`make lint`) which is based on [`elisp-lint`](https://github.com/gonewest818/elisp-lint) and includes
  - [byte-compilation](https://www.gnu.org/software/emacs/manual/html_node/elisp/Byte-Compilation.html), [`checkdoc`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Tips.html), [check-declare](https://www.gnu.org/software/emacs/manual/html_node/elisp/Declaring-Functions.html), packaging metadata, indentation, and trailing whitespace checks.
- [ ] You've updated the [changelog](../blob/master/CHANGELOG.md) (if adding/changing user-visible functionality)
- [ ] You've updated the [user manual](../blog/master/doc) (if adding/changing user-visible functionality)

Thanks!

*If you're just starting out to hack on CIDER you might find this [section of its
manual][1] extremely useful.*

[1]: https://cider.readthedocs.io/en/latest/hacking_on_cider/

### CODE REVIEW

**Comment by fhalde** [comment]
the CI is failing because of some error in the CI configuration it seems

```
The command "cask_install_or_reset" failed 3 times.
The command "sh travis-ci/install-cask.sh" failed and exited with 1 during .
```

**Comment by bbatsov** [comment]
What's the problem this command would solve?

**Comment by fhalde** [comment]
with `cider-repl-set-ns`, the REPL namespace is switched .. more often i'd want the buffer to be loaded in the REPL without changing the existing namespace of the REPL.

this basically does a `(require '[a.b.c] :as something)` and you can straightaway start using it as `something/somefn` e.t.c

@bbatsov

**Comment by bbatsov** [comment]
I'm not sure that a command for this will help much, though. Seems to me that writing the require manually is more or less the same effort. I'll think about this.

**Comment by benedekfazekas** [comment]
would the user need to type the ns and the alias or does this provide some defaults (sorry only read the comment thread here, not the code)

**Comment by bbatsov** [comment]
Now you have to type it, but if we provide some defaults that might make the feature a bit more useful.

**Comment by benedekfazekas** [comment]
agreed

**Comment by fhalde** [comment]
will work on the default .. thinking of using the first letter of ever word in the namespace
i.e. `hello.world` will become `hw` or `www.users.handlers` will become `wuh`

let me know your thoughts

**Comment by benedekfazekas** [comment]
i would go for the last word rather. but question of taste/style so your approach is fine too

**Comment by fhalde** [comment]
@alexander-yakushev my goal was to require it in the current REPL's namespace & yes the name `cider-repl-set-ns-as` does look misleading if I think about it now

**Pull request closed without merging**
