### PR TITLE
Add instructions for using Figwheel with jack-in

### PR DESCRIPTION
**Pull request by magnars**
Figwheel is very popular and should probably have its own section in the Readme. :)

### CODE REVIEW

**Comment by benedekfazekas** [comment]
+1

**Comment by Malabarba** [comment]
LGTM 👍

**Comment by bbatsov** [comment]
:+1:

**Comment by bbatsov** [comment]
Btw, it'd be nice if someone added similar instructions for boot. I assume the bulk of the setup is the same.

**Comment by benedekfazekas** [comment]
i may be wrong but afaik you don't really need figwheel if you run with boot as it has very similar features for cljs.

**Pull request merged**
