### PR TITLE
Debug on exception

### PR DESCRIPTION
**Pull request by bo-tato**
Add support on the cider side to go with https://github.com/clojure-emacs/cider-nrepl/pull/769
passing a negative argument to `cider-eval-defun-at-point` will instrument it with #dbgexn
also added some documentation to the debugger docs describing the new feature

-----------------

Before submitting the PR make sure the following things have been done (and denote this
by checking the relevant checkboxes):

- [ ] The commits are consistent with our [contribution guidelines](../blob/master/.github/CONTRIBUTING.md)
- [ ] You've added tests (if possible) to cover your change(s)
- [ ] All tests are passing (`eldev test`)
- [ ] All code passes the linter (`eldev lint`) which is based on [`elisp-lint`](https://github.com/gonewest818/elisp-lint) and includes
  - [byte-compilation](https://www.gnu.org/software/emacs/manual/html_node/elisp/Byte-Compilation.html), [`checkdoc`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Tips.html), [check-declare](https://www.gnu.org/software/emacs/manual/html_node/elisp/Declaring-Functions.html), packaging metadata, indentation, and trailing whitespace checks.
- [ ] You've updated the [changelog](../blob/master/CHANGELOG.md) (if adding/changing user-visible functionality)
- [ ] You've updated the [user manual](../blob/master/doc) (if adding/changing user-visible functionality)

Thanks!

*If you're just starting out to hack on CIDER you might find this [section of its
manual][1] extremely useful.*

[1]: https://docs.cider.mx/cider/contributing/hacking.html

### CODE REVIEW

**Comment by bbatsov** [comment]
@yuhan0 I guess you'll take this from here, right?

**Comment by yuhan0** [comment]
How do you feel about this proposal of overloading cider-eval-defun with a negative argument? 
I find that sort of API quite bad for discoverability - in my personal config I have these custom commands instead, along with similar ones for various other temporary debugging forms - basically generalizing the existing `cider--prompt-and-insert-inline-dbg` interface.

```clj
;; * Insert #break / #dbg reader forms
(defun +cider-insert-dbg (ex)
  "Insert #dbg reader.
If EX is non nil or called with prefix arg, insert #dbg! to break on exception.
Automatically reevaluates form if inside a defn."
  (interactive "P")
  (unless (looking-at-p "(")
    (backward-up-list))
  (cider-insert-fragile-reader-macro
   (if ex "#dbg!"
     (concat "#dbg"
             (let ((cond (cider-read-from-minibuffer "Condition: ")))
               (unless (equal "" cond)
                 (format " ^{:break/when %s}" cond))))))
  (when (clojure-top-level-form-p "defn")
    (cider-eval-defun-at-point)))

(defun +cider-insert-breakpoint (ex)
  "Insert #break reader.
If EX is non nil or called with prefix arg, insert #break! to break on exception."
  (interactive "P")
  (cider-insert-fragile-reader-macro
   (if ex "#break!"
     (concat "#break"
             (let ((cond (cider-read-from-minibuffer "Condition: ")))
               (unless (equal "" cond)
                 (format " ^{:break/when %s}" cond)))))))

```

**Comment by yuhan0** [comment]
A quick demo of what that looks like in practice
https://github.com/clojure-emacs/cider/assets/22216124/8e0440e4-da2c-4de0-890d-8d882185719a

**Comment by bbatsov** [comment]
> How do you feel about this proposal of overloading cider-eval-defun with a negative argument?

I'm not a big fan of prefix arguments in general, but from time to time they fit in nicely. Definitely not a big fan of the negative argument, as it's probably the hardest to discover organically by users. I'm ok with adding some special commands and I guess we can have something with prefix arguments as well, for whoever prefers them, given that it adds little complexity.

The demo looks good to me.

**Comment by bbatsov** [comment]
@yuhan0 Any chance you'll have time for this soon? I think it's the only feature remaining for the next CIDER release.

**Comment by yuhan0** [comment]
Yes, I have the working code for this feature but unfortunately don't have much time over the next couple of days to work on testing / refining it into a PR. If it's a blocker for a release maybe I'll push those commits now and see if anyone can take it from there? Might be able to do something over the weekend too.

**Comment by bbatsov** [comment]
@yuhan0 No rush, there's one more blocker anyways (https://github.com/clojure-emacs/cider/issues/3365). If you can spend some time on this over the weekend that'd be great. 

I'll close this PR in favor of #3366 that you've opened just now.

**Pull request closed without merging**
