### PR TITLE
Test warnings

### PR DESCRIPTION
**Pull request by Malabarba**

### CODE REVIEW

**Comment by Malabarba** [comment]
Crap. I'm clearly doing something wrong, probably in how I'm trying to use cask.

**Comment by Malabarba** [comment]
Yes! I have defeated Travis.

**Comment by expez** [comment]
gold-star

**Comment by Malabarba** [comment]
Refactored to a script file.

**Comment by Malabarba** [comment]
Why does evm produce an Emacs where all the source files are newer than the elc files? It adds a ton of noise to the build. :P

**Comment by bbatsov** [comment]
Maybe an EVM bug?

**Comment by Malabarba** [comment]
I'll get in touch with them. Still, that's irrelevant to this PR. Way we merge?

**Comment by bbatsov** [comment]
Guess we can. Next step - a checkdoc task. :-)

**Comment by Malabarba** [comment]
FTR https://github.com/rejeep/evm/issues/58#issuecomment-143194863

**Pull request merged**
