### PR TITLE
Update "Using Boot" setup instructions

### PR DESCRIPTION
**Pull request by fromheten**

### CODE REVIEW

**Comment by Malabarba** [comment]
Is there a particular reason for this? In general I don't think the readme should tell people to use the snapshot.

**Comment by bbatsov** [comment]
Yeah, the readme should not promote the snapshots.

**Comment by fromheten** [comment]
The reason was that I updated Cider, and it complained that cider-nrepl was out of date. Sorry, I should have written that in the description.

**Comment by bbatsov** [comment]
Yeah, but you've updated to the snapshot release (probably from melpa) and in general we avoid promoting its usage. This is why the readme always suggests the latest stable version in setup examples.

**Pull request closed without merging**
