### PR TITLE
Fix info lookup

### PR DESCRIPTION
**Pull request by plexus**
When doing a var-info lookup we potentially try three different strategies:
info, lookup, and eval. The second currently always fails, because the "info"
dict is not at the top level in the response message, but nested under an "info"
key.

Compare and contrast:

```emacs-lisp
 (cider-sync-request:info "clojure.core/str")
 (cider-sync-request:lookup "clojure.core/str")
 (cider-fallback-eval:info "clojure.core/str")
```

Running tests locally I get a failure, but it seems unrelated.

```
cider-repls when multiple sessions exist always returns the most recently used connection

Traceback (most recent call last):
  buttercup-fail("%s" "Expected `(cider-repls)' to be `equal' to `(#<buffer *b-session:b2:cljs*(8228)> #<buffer *b-session:b1:clj*(7432)>)', but instead it was `(#<buffer *a-session:bb2:cljs*(8909)> #<buffer *a-session:bb1:clj*(4337)>)' which does not match because: (list-elt 0 (different-atoms #<buffer *a-session:bb2:cljs*(8909)> #<buffer *b-session:b2:cljs*(8228)>)).")
  signal(buttercup-failed "Expected `(cider-repls)' to be `equal' to `(#<buffer *b-session:b2:cljs*(8228)> #<buffer *b-session:b1:clj*(7432)>)', but instead it was `(#<buffer *a-session:bb2:cljs*(8909)> #<buffer *a-session:bb1:clj*(4337)>)' which does not match because: (list-elt 0 (different-atoms #<buffer *a-session:bb2:cljs*(8909)> #<buffer *b-session:b2:cljs*(8228)>)).")
FAILED: Expected `(cider-repls)' to be `equal' to `(#<buffer *b-session:b2:cljs*(8228)> #<buffer *b-session:b1:clj*(7432)>)', but instead it was `(#<buffer *a-session:bb2:cljs*(8909)> #<buffer *a-session:bb1:clj*(4337)>)' which does not match because: (list-elt 0 (different-atoms #<buffer *a-session:bb2:cljs*(8909)> #<buffer *b-session:b2:cljs*(8228)>)).
```

-----------------

Before submitting the PR make sure the following things have been done (and denote this
by checking the relevant checkboxes):

- [x] The commits are consistent with our [contribution guidelines](../blob/master/.github/CONTRIBUTING.md)
- [ ] You've added tests (if possible) to cover your change(s)
- [x] All tests are passing (`eldev test`)
- [x] All code passes the linter (`eldev lint`) which is based on [`elisp-lint`](https://github.com/gonewest818/elisp-lint) and includes
  - [byte-compilation](https://www.gnu.org/software/emacs/manual/html_node/elisp/Byte-Compilation.html), [`checkdoc`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Tips.html), [check-declare](https://www.gnu.org/software/emacs/manual/html_node/elisp/Declaring-Functions.html), packaging metadata, indentation, and trailing whitespace checks.
- [x] You've updated the [changelog](../blob/master/CHANGELOG.md) (if adding/changing user-visible functionality)
- [ ] You've updated the [user manual](../blob/master/doc) (if adding/changing user-visible functionality)

Thanks!

*If you're just starting out to hack on CIDER you might find this [section of its
manual][1] extremely useful.*

[1]: https://docs.cider.mx/cider/contributing/hacking.html

### CODE REVIEW

**Comment by bbatsov** [comment]
Looks good, but you will need to rebase.

**Comment by plexus** [comment]
Rebased!

**Comment by plexus** [comment]
You'll notice I also fixed some more linter warnings that I was getting locally but not on CI. Maybe cause I'm on a more recent Emacs build? (I tend to build from master, last time was end of July).

**Comment by bbatsov** [comment]
Thanks!

**Pull request merged**
