### PR TITLE
Fix spelling error in clj-refactor section of documentation

### PR DESCRIPTION
**Pull request by gganley**
Made a mistake in my last PR in clumping together unrelated commits. Changed a small spelling mistake in the explanation of "clj-refactor" in "Additional Packages"

### CODE REVIEW

**Comment by bbatsov** [comment]
Thanks for spotting this. Please change the commit message to "Fix spelling ..." to match our conventions.

**Comment by gganley** [comment]
I couldn't find a file akin to CONTRIBUTERS.md. Would you mind pointing it out to me?

**Comment by bbatsov** [comment]
See http://chris.beams.io/posts/git-commit/ and https://github.com/clojure-emacs/cider/blob/master/.github/CONTRIBUTING.md

**Comment by dpsutton** [comment]
https://github.com/clojure-emacs/cider/blob/master/.github/CONTRIBUTING.md

its in the .github folder

**Pull request merged**
