### PR TITLE
nrepl-client.el (nrepl-send-sync-request): New optional argument

### PR DESCRIPTION
**Pull request by Malabarba**
If provided, abort the loop immediately and return nil. This avoids
hanging the interface on background requests.

### CODE REVIEW

**Comment by Malabarba** [comment]
Posted it now to let the tests run, I haven't actually tested if ti fixes the lag yet. Can only try it at home.

**Comment by bbatsov** [comment]
Looking forward to the results of your experiment!

**Comment by Malabarba** [comment]
Took me a while because of stupid -when-let. But now I can confirm it works for me. Also added some minor changes to another function.

**Comment by bbatsov** [comment]
:+1:

**Pull request merged**
