### PR TITLE
Upgrade cider-nrepl

### PR DESCRIPTION
**Pull request by vemv**
Upgrades `cider-nrepl`, `Orchard` and `clj-suitable` for pulling their latest bugfixes.

### CODE REVIEW

**Comment by bbatsov** [comment]
Thanks!

**Comment by vemv** [comment]
🍻! Could we let me know as it hits MELPA? Not familiar with the release process

**Comment by bbatsov** [comment]
MELPA rebuilds the packages automatically every few hours.

**Comment by vemv** [comment]
Ah nice. What about the CHANGELOG? Should it be updated to say sth other than `master`?

**Comment by bbatsov** [comment]
Nope, this is just a snapshot release built automatically from `master`. The 1.2 release will likely happen around the end of the month, provided nREPL 0.9 is finalized by then.

**Pull request merged**
