### PR TITLE
[Fix #2058] Don't cache non-existing ns-forms

### LINKED ISSUE #2058: `cider-load-buffer` throws an error for buffers without a ns form
## Expected behavior

Evaluate the buffer.

## Actual behavior

Throws an error.

## Steps to reproduce the problem

Load any Clojure file and then invoke: `M-x cider-load-buffer`.

Here's the stack trace:
```lisp
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  string-match("^[ 	\n]*(ns[ 	\n]+\\([^][ 	\n(){}]+\\)" nil)
  cider-ns-from-form(nil)
  cider-repl--cache-ns-form(nil #<buffer *cider-repl clj-nlp-parse*>)
  (closure ((ns-form) (filename . "/Users/landes/view/lein/src/init.clj") (buffer . #<buffer init.clj>) t) (connection) (cider-repl--cache-ns-form ns-form connection) (cider-request:load-file (cider-file-string filename) (funcall cider-to-nrepl-filename-function (cider--server-filename filename)) (file-name-nondirectory filename) connection))(#<buffer *cider-repl clj-nlp-parse*>)
  cider-map-connections((closure ((ns-form) (filename . "/Users/landes/view/lein/src/init.clj") (buffer . #<buffer init.clj>) t) (connection) (cider-repl--cache-ns-form ns-form connection) (cider-request:load-file (cider-file-string filename) (funcall cider-to-nrepl-filename-function (cider--server-filename filename)) (file-name-nondirectory filename) connection)) :both)
  (let ((filename (buffer-file-name buffer)) (ns-form (cider-ns-form))) (cider-map-connections (function (lambda (connection) (cider-repl--cache-ns-form ns-form connection) (cider-request:load-file (cider-file-string filename) (funcall cider-to-nrepl-filename-function (cider--server-filename filename)) (file-name-nondirectory filename) connection))) :both) (message "Loading %s..." filename))
  (save-current-buffer (set-buffer buffer) (if buffer-file-name nil (user-error "Buffer `%s' is not associated with a file" (current-buffer))) (if (and cider-save-file-on-load (buffer-modified-p) (or (eq cider-save-file-on-load t) (y-or-n-p (format "Save file %s? " buffer-file-name)))) (progn (save-buffer))) (remove-overlays nil nil (quote cider-temporary) t) (cider--clear-compilation-highlights) (cider--quit-error-window) (let ((filename (buffer-file-name buffer)) (ns-form (cider-ns-form))) (cider-map-connections (function (lambda (connection) (cider-repl--cache-ns-form ns-form connection) (cider-request:load-file (cider-file-string filename) (funcall cider-to-nrepl-filename-function (cider--server-filename filename)) (file-name-nondirectory filename) connection))) :both) (message "Loading %s..." filename)))
  cider-load-buffer()
  funcall-interactively(cider-load-buffer)
  call-interactively(cider-load-buffer record nil)
  command-execute(cider-load-buffer record)
  execute-extended-command(nil "cider-load-buffer" nil)
  funcall-interactively(execute-extended-command nil "cider-load-buffer" nil)
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```
## Environment & Version information

* Emacs 25.2
* macOS Sierra

### CIDER version information

```
;; CIDER 0.15.0 (London), nREPL 0.2.12
;; Clojure 1.8.0, Java 1.8.0_141
```

### Lein/Boot version

*E.g. Lein 2.6.1* (skip this when you didn't start the nREPL server
using Lein or Boot)

### Emacs version

GNU Emacs 25.2.1 (x86_64-apple-darwin16.7.0, NS appkit-1504.83 Version 10.12.6 (Build 16G29)) of 2017-07-20

### Operating system

macOS Sierra

### PR DESCRIPTION
**Pull request by vspinu**

### CODE REVIEW

**Comment by vspinu** [comment]
I am adding one extra fix for broken eval in the case when cljc file is connected to only one connection.  It throws `If you don’t know what that means, you probably need to jack-in (‘C-c M-j’).`  I have no idea how I missed this case during my tests for 746e4d694104c.

**Comment by bbatsov** [comment]
Both changes look good and should have changelog entries now that 0.15 is out and we'll likely issue a bugfix release for them. 

Perhaps adding a few unit tests for those changes would be a good idea as well - I'd like us to avoid regressions in the future.

**Comment by vspinu** [comment]
Done. I have documented the changes and added a couple of tests. A few notes though. 

First fix is mostly a temporary workaround. The bug emerged because `cider-map-connections` ended up calling `cider-current-connection` with "multi" argument, which is not the intended nor documented use of that function. At the least it should be `any`.  I will streamline connection API within a week or two, time permitting, and will remove `cider-map-connections` entirely. Will add more tests then. Till then this one is good enough.

The other minor point is that I bulked two more tests to cider-client-test which are more suitable to cider-interaction-tests. That because I couldn't figure out how to extract common utility macros into a separate library within buttercup's tests/ dir. The tests dir is not added by butercup to the load path.

**Comment by bbatsov** [comment]
> First fix is mostly a temporary workaround. The bug emerged because cider-map-connections ended up calling cider-current-connection with "multi" argument, which is not the intended nor documented use of that function. At the least it should be any. I will streamline connection API within a week or two, time permitting, and will remove cider-map-connections entirely. Will add more tests then. Till then this one is good enough.

Sounds good to me.

> The other minor point is that I bulked two more tests to cider-client-test which are more suitable to cider-interaction-tests. That because I couldn't figure out how to extract common utility macros into a separate library within buttercup's tests/ dir. The tests dir is not added by butercup to the load path.

Interesting point. I thought something like this should be trivial.

**Pull request merged**
