### PR TITLE
Avoid hitting keyservers.net if key already in cache

### PR DESCRIPTION
**Pull request by dickmao**
Check we already have the desired elpa key before spamming keyservers.net.

### CODE REVIEW

**Comment by bbatsov** [comment]
Where exactly is the check? I just see that the sleep was made conditional now.

**Comment by dickmao** [comment]
Before PR: 1. hit keyserver 2. check if key retrieved 3. if not, wait before retrying
After PR: 1. check if key retrieved 2. if not, wait if this is reattempt 3. hit keyserver

**Comment by bbatsov** [comment]
Ah, got it. The way the loop's written I got confused. I'm too old for bash scripts. :D Guess similar update should be made to the docker images. //cc @Silex

**Comment by Silex** [comment]
@bbatsov: fixed by https://github.com/Silex/docker-emacs/commit/36989a8f06483d0f3455d36028200ae5dc3b78cd

**Pull request merged**
