### PR TITLE
Optionally pass repl-type to cider-insert-in-repl

### PR DESCRIPTION
**Pull request by arichiardi**
Necessary in case you want to override the autodetection, which at the moment
is flimsy.

-----------------

Before submitting the PR make sure the following things have been done (and denote this
by checking the relevant checkboxes):

- [X] The commits are consistent with our [contribution guidelines][1]

### CODE REVIEW

**Comment by bbatsov** [comment]
I don't get the point of this change, so some explanations would be welcome. You think the connection dispatch is not picking the right REPL or what?

**Comment by arichiardi** [comment]
@bbatsov yes when I try to invoke the function it seems that the REPL type is not identified correctly (with `shadow`), so I need to pass `"clj"` in. This is also good for completeness.

**Comment by arichiardi** [comment]
Rebased and fixed the linter.

**Comment by bbatsov** [comment]
> @bbatsov yes when I try to invoke the function it seems that the REPL type is not identified correctly (with shadow), so I need to pass "clj" in. This is also good for completeness.

The current repl type should be clear from the file you're visiting, so I don't think this is a good idea. Shouldn't you use `cider-set-repl-type` instead to fix the incorrect repl type?

**Comment by arichiardi** [comment]
I am using the function `cider-insert-in-repl` to send my own string from the code buffer to the REPL, but the function contains `current-repl-buffer`, which fails for `shadow`. This is why I need to kind of override...Maybe the new `defcustom` there might help actually...

**Comment by arichiardi** [comment]
@bbatsov I copied that function over to my local code. I still feel this should go in to solve the current mismatch between the visited buffer and the underlying REPL. The scenario is this, which I know is handled in another way in `cider`, but I am going to write here again anyways:

 * open terminal
 * launch clojure REPL
 * connect to it with `cider-connect`
 * try to send an upgrade form from a cljs buffer *fail* - no "cljs" buffer found

Probably @vspinu has a better way to handle this now.

**Comment by arichiardi** [comment]
this is what I am using for insertion now:

```
(with-current-buffer (cider-current-repl "clj")
      (goto-char (point-max))
      (let ((beg (point)))
        (insert form)
        (indent-region beg (point)))
      (cider-repl-return))
```

**Comment by arichiardi** [comment]
Alternative to manual insertion:

```
(cider-register-cljs-repl-type
   'shadow-select
   #'ar-emacs-cljs-shadow-select-init-form
   #'cider-check-shadow-cljs-requirements)
```

**Comment by arichiardi** [comment]
No, too soon:

`user-error: No cljs REPLs found.  Have you linked a session?`

Really need help on this one.

**Comment by arichiardi** [comment]
Oh right, so now I need to detect the REPL - switch on auto detection again ;)

**Comment by arichiardi** [comment]
I think I found an alternative but you are right it should be fixed properly. Closing.

**Pull request closed without merging**
