### PR TITLE
Dynamic indent

### PR DESCRIPTION
**Pull request by Malabarba**
Obviously this functionality still needs documentation, but I wanted to put the code up here for people to see.
Also, this relies on the yet-unmerged https://github.com/clojure-emacs/clojure-mode/pull/320

### CODE REVIEW

**Comment by Malabarba** [comment]
I decided to completely ditch the part about reading arglists. Because of all those optional arguments like `attr?` or `opts+spec`, this would take way too much work to implement.

**Comment by bbatsov** [comment]
Fair enough. I'm all for simplicity.

**Comment by bbatsov** [comment]
This has to be rebased.

**Comment by Malabarba** [comment]
Done.

**Pull request merged**
