### PR TITLE
Fix arity of `cider-change-buffers-designation'

### PR DESCRIPTION
**Pull request by danielsz**
Before submitting a PR make sure the following things have been done (and denote this
by checking the relevant checkboxes):

- [x] The commits are consistent with our [contribution guidelines](CONTRIBUTING.md)
- [x] You've added tests (if possible) to cover your change(s)
- [x] All tests are passing (`make test`)
- [x] The new code is not generating bytecode or `M-x checkdoc` warnings
- [ ] You've updated the changelog (if adding/changing user-visible functionality)
- [ ] You've updated the readme (if adding/changing user-visible functionality)
- [ ] You've updated the refcard (if you made changes to the commands listed there)

Thanks!

* Allow user to set the argument of `cider-change-buffers-designation'
  in a non-interactive call (programmatically).

### CODE REVIEW

**Comment by bbatsov** [comment]
Seems to me the current commit message is a bit misleading, your description illustrates the actual gist of the change "Allow user to set the argument of `cider-change-buffers-designation' in a non-interactive call (programmatically)".

**Comment by danielsz** [comment]
Hi Bozhidar, 

I have no intentions to mislead, only to communicate. 
If I failed to do so clearly, please help me out with a question of what you think should be restated. 
If I had to guess, I would say you don't understand the reason for this PR, right? You want a use case. 

So the use case for this PR is that I want to call  `cider-change-buffers-designation` in an Emacs Lisp script. It is as simple as that. Before the PR, `cider-change-buffers-designation` only works interactively. After the PR, `cider-change-buffers-designation` works both interactively, and as a regular function that takes an argument.

Furthermore, it is just better Emacs Lisp and closer to the spirit of functional programming. Why does that function hide user input in local state? Why doesn't it leverage the standard `interactive` facility?  You can see the benefits immediately, as they simplify the tests. When the function accepts an argument, you don't need no fancy `noflet` form to advise around the user input gathering. 

The takeaway is that when local state in a function comes from user input, it should always be an argument of that function. The function will be more versatile, will better the chances to be free of side-effects, will be easier to read and test. Emacs Lisp provides a structured approach to apply this principle via the `interactive` form.

Thank you.

**Comment by bbatsov** [comment]
I never doubted the benefit of the PR itself, I just disliked the commit message. Anyways, I changed it myself. Thanks!

**Comment by danielsz** [comment]
:+1: Thank you!

**Pull request merged**
