### PR TITLE
Simplify connection tracking code

### PR DESCRIPTION
**Pull request by Malabarba**
Might affect #1266 and #1263.

`cider-find-connection-buffer-for-project-directory` embraces
ambiguities instead of avoiding them. By returning the first of multiple
matching buffers, it plays nice with the sibling connections.
It also returns buffers with nil directories if nothing else matches,
but this is just to try to fail as little as possible, it has nothing to
do with siblings.

`cider-switch-to-relevant-repl-buffer` just calls
`cider-current-repl-buffer` directly. This allows it to work in sibling
connections without complaining.

### CODE REVIEW

**Comment by bbatsov** [comment]
I'm all for simplification of the current algorithm, but I find the notion of the "most recent connection". Looking at the code "most recent" is the connection that was prepended last to `cider-connections`, but some people might have trouble understanding this.

**Comment by Malabarba** [comment]
We could change the doc to say "an arbitrary one is returned" instead of "most recent". Just so people don't rely on this functionality.

**Comment by bbatsov** [comment]
My main concern is that from time to time someone would like to bind such an edge case to a particular project and they'll have trouble figuring this out. Right now using "make default connection" would make something the "most recent connection", but that's obviously not super clear.

**Comment by Malabarba** [comment]
We could also extend the docstring with more explanation of what "recent" means and linking to `make-default-connection`.

**Comment by bbatsov** [comment]
Probably that'd be the best short-term solution.

**Comment by Malabarba** [comment]
Updated.

**Comment by bbatsov** [comment]
:+1:

**Pull request merged**
