### PR TITLE
Backported fixes for a 0.10.1 release

### PR DESCRIPTION
**Pull request by cap10morgan**

### CODE REVIEW

**Comment by Malabarba** [comment]
Something is a bit odd here. I think The commit "Require cider.nrepl.print-method upon connecting" is already part of the 0.10.0 release tag. Should it be showing up on this PR?

**Comment by cap10morgan** [comment]
I started from the v0.10.0 tag. Did the release contain more commits than that or this branch fewer?

**Comment by Malabarba** [comment]
It's ok. I think the `v0.10` branch just wasn't created from the `v0.10.0` tag, it was created from a commit a couple of steps behind the tag. That's why a couple of commits which were already in the `v0.10.0` tag are showing up here.
Anyway, it's harmless. These are commits which should be in the `v0.10` branch anyway.

**Comment by bbatsov** [comment]
> I think the v0.10 branch just wasn't created from the v0.10.0 tag,

Actually it was created from the tag, but it seems the tag hasn't changed for me when you update it upstream.

**Comment by cap10morgan** [comment]
@bbatsov OK, I think everything is taken care of in here now.

If you point me to the cider-nrepl commit and setup a `v0.10` branch in that repo, I'd be happy to issue a PR for that too. Should I backport all other master bug fixes there too?

**Comment by bbatsov** [comment]
> If you point me to the cider-nrepl commit and setup a v0.10 branch in that repo, I'd be happy to issue a PR for that too.

Branch created. 

> Should I backport all other master bug fixes there too?

The more bugfixes - the better.

**Comment by cap10morgan** [comment]
@bbatsov Great, thanks.

Is there a changelog somewhere for cider-nrepl or should I just go through the master commits post release and pull in the ones that seem like bug fixes?

**Comment by cap10morgan** [comment]
Or would it make sense to create a `v0.10.1` milestone in both projects and start putting issues into them?

**Comment by cap10morgan** [comment]
Hmm, I just fired up a REPL with this code and tried to run `(java.util.UUID/randomUUID)` and got this error:

```
Debugger entered--Lisp error: (wrong-number-of-arguments ((cider-buffer-ns cl-struct-nrepl-response-queue-tags t) (buffer value-handler stdout-handler stderr-handler done-handler &optional eval-error-handler) "Make a response handler for connection BUFFER.
A handler is a function that takes one argument - response received from
the server process.  The response is an alist that contains at least 'id'
and 'session' keys.  Other standard response keys are 'value', 'out', 'err'
and 'status'.

The presence of a particular key determines the type of the response.  For
example, if 'value' key is present, the response is of type 'value', if
'out' key is present the response is 'stdout' etc.  Depending on the type,
the handler dispatches the appropriate value to one of the supplied
handlers: VALUE-HANDLER, STDOUT-HANDLER, STDERR-HANDLER, DONE-HANDLER, and
EVAL-ERROR-HANDLER.  If the optional EVAL-ERROR-HANDLER is nil, the default
`nrepl-err-handler' is used.  If any of the other supplied handlers are nil
nothing happens for the corresponding type of response.

When `nrepl-log-messages' is non-nil, *nrepl-messages* buffer contains
server responses." (function (lambda (response) (let ((value (nrepl-dict-get response "value")) (ns (nrepl-dict-get response "ns")) (out (nrepl-dict-get response "out")) (err (nrepl-dict-get response "err")) (status (nrepl-dict-get response "status")) (id (nrepl-dict-get response "id")) (pprint-out (nrepl-dict-get response "pprint-out"))) (if (buffer-live-p buffer) (progn (save-current-buffer (set-buffer buffer) (if (and ns (not (derived-mode-p (quote clojure-mode)))) (progn (cider-set-buffer-ns ns)))))) (cond (value (if value-handler (progn (funcall value-handler buffer value)))) (out (if stdout-handler (progn (funcall stdout-handler buffer out)))) (pprint-out (if stdout-handler (progn (funcall stdout-handler buffer pprint-out)))) (err (if stderr-handler (progn (funcall stderr-handler buffer err)))) (status (if (member "interrupted" status) (progn (message "Evaluation interrupted."))) (if (member "eval-error" status) (progn (funcall (or eval-error-handler nrepl-err-handler)))) (if (member "namespace-not-found" status) (progn (message "Namespace not found."))) (if (member "need-input" status) (progn (cider-need-input buffer))) (if (member "done" status) (progn (nrepl--mark-id-completed id) (if done-handler (progn (funcall done-handler buffer))))))))))) 7)
  nrepl-make-response-handler(#<buffer *cider-repl voting-method-works*> (closure ((buffer . #<buffer *cider-repl voting-method-works*>) cider-mode t) (buffer value) (if cider-repl-use-pretty-printing nil (cider-repl-emit-result buffer value t))) (closure ((buffer . #<buffer *cider-repl voting-method-works*>) cider-mode t) (buffer out) (cider-repl-emit-stdout buffer out)) (closure ((buffer . #<buffer *cider-repl voting-method-works*>) cider-mode t) (buffer err) (cider-repl-emit-stderr buffer err)) (closure ((buffer . #<buffer *cider-repl voting-method-works*>) cider-mode t) (buffer) (cider-repl-emit-prompt buffer)) cider-default-err-handler (closure ((buffer . #<buffer *cider-repl voting-method-works*>) cider-mode t) (buffer pprint-out) (cider-repl-emit-result buffer pprint-out nil)))
  cider-repl-handler(#<buffer *cider-repl voting-method-works*>)
  (cider-eval-spinner-handler (current-buffer) (cider-repl-handler (current-buffer)))
  (cider-nrepl-request:eval input (cider-eval-spinner-handler (current-buffer) (cider-repl-handler (current-buffer))) (cider-current-ns) (line-number-at-pos input-start) (cider-column-number-at-pos input-start))
  (if (and (not (string-match-p "\\`[ 	
\n]*\\'" input)) cider-repl-use-pretty-printing) (cider-nrepl-request:pprint-eval input (cider-eval-spinner-handler (current-buffer) (cider-repl-handler (current-buffer))) (cider-current-ns) (1- (window-width))) (cider-nrepl-request:eval input (cider-eval-spinner-handler (current-buffer) (cider-repl-handler (current-buffer))) (cider-current-ns) (line-number-at-pos input-start) (cider-column-number-at-pos input-start)))
  (let ((input (cider-repl--current-input)) (input-start (save-excursion (cider-repl-beginning-of-defun) (point)))) (goto-char (point-max)) (cider-repl--mark-input-start) (cider-repl--mark-output-start) (cider-spinner-start) (if (and (not (string-match-p "\\`[ 	
\n]*\\'" input)) cider-repl-use-pretty-printing) (cider-nrepl-request:pprint-eval input (cider-eval-spinner-handler (current-buffer) (cider-repl-handler (current-buffer))) (cider-current-ns) (1- (window-width))) (cider-nrepl-request:eval input (cider-eval-spinner-handler (current-buffer) (cider-repl-handler (current-buffer))) (cider-current-ns) (line-number-at-pos input-start) (cider-column-number-at-pos input-start))))
  cider-repl--send-input(t)
  (cond (end-of-input (cider-repl--send-input)) ((and (get-text-property (point) (quote cider-old-input)) (< (point) cider-repl-input-start-mark)) (cider-repl--grab-old-input end-of-input) (cider-repl--recenter-if-needed)) ((cider-repl--input-complete-p cider-repl-input-start-mark (point-max)) (cider-repl--send-input t)) (t (cider-repl-newline-and-indent) (message "[input not complete]")))
  cider-repl-return(nil)
  call-interactively(cider-repl-return nil nil)
  command-execute(cider-repl-return)
```

**Comment by cap10morgan** [comment]
According to `git bisect` [this is the first bad commit](https://github.com/cap10morgan/cider/commit/ea459143a99e230f359366478ce8adfea20101ba) and I bet that's because we also need to pull in [this commit](https://github.com/clojure-emacs/cider/commit/042662cade69f94d56186cc0882ec388365155b3).

I'll pull that commit in too.

**Comment by cap10morgan** [comment]
Yep, that problem is now fixed.

**Comment by Malabarba** [comment]
👍

**Comment by bbatsov** [comment]
:+1: 

Let's see if we'll manage to get more fixes in over the weekend and we can do the new release early next week.

**Comment by bbatsov** [comment]
I've also added a v0.10.1 milestone.

**Pull request merged**
