### PR TITLE
Fix read-directory invocation the *right* way.

### LINKED ISSUE #1356: Weird prompt when associating connection with directory
This is the prompt that I get when I `cider-connect` and chose to associate the connection with a directory (the cursor is between those two `//`):

    Project directory: ~/path/to/cider-nreplh//home/artur/path/to/cider-nrepl/

I should say that the prompt works. I can just hit `RET` and the directory used will be `/home/artur/path/to/cider-nrepl/`. But it's certainly not optimal.

I'm guessing this is due to #1326. @Peeja do you have this too?

### PR DESCRIPTION
**Pull request by Peeja**
Improves #1326.
Fixes #1356.

### CODE REVIEW

**Comment by bbatsov** [comment]
Are you sure? Isn't this where we started from? :-)

**Comment by Peeja** [comment]
Close. :)

```diff
- (read-directory-name "Project directory: " nil (clojure-project-dir))
+ (read-directory-name "Project directory: " (clojure-project-dir))
```

**Comment by bbatsov** [comment]
OK, I've read the docstring again and your fix seems reasonable. Just drop the `.` from the commit message's title.

**Comment by Peeja** [comment]
Okay, that seems odd to me, but if that's the style guide… :)

**Comment by bbatsov** [comment]
Take a look here http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

**Comment by Peeja** [comment]
That's my personal commit message style guide too, but it doesn't say anything about periods, does it? It just says to limit the subject line to 50 characters, unless I'm missing something.

**Comment by Malabarba** [comment]
It doesn't say it exploicitly, but the summary line in the example doesn't end in a period.

**Comment by Peeja** [comment]
I suppose. Personally, I prefer to end my sentences with periods in all cases, but I'm happy to defer to the project's standards.

**Comment by bbatsov** [comment]
The first line of a commit message is a title, not a sentence.

**Comment by Peeja** [comment]
Huh, is it weird that reading that makes me feel better about the whole thing? You've convinced me. Body text has periods, headlines don't. If it's good enough for the NY Times, it's good enough for me. :+1:

**Pull request merged**
