### PR TITLE
Integrate overlays with interactive evaluation

### LINKED ISSUE #1196: Expose an option to display interactive eval results results using an overlay
Basically it'd be awesome if everyone could use @Malabarba's debug overlay display for regular interactive evaluation. This should be an option, alternative to the current display of results in the minibuffer.

### PR DESCRIPTION
**Pull request by Malabarba**
Closes #1196

### CODE REVIEW

**Comment by bbatsov** [comment]
Just one comment from me - won't it better to have the option select either `minibuffer`, `overlays` or `both` as the result's display scheme. Generally I'd never opt to use them both at the same time, as dislike information redundancy. I guess others might share my feelings on the subject.

**Comment by Malabarba** [comment]
> Just one comment from me - won't it better to have the option select either minibuffer, overlays or both as the result's display scheme

Done. I also set the default duration of overlays to be "until next command" which mimics the echo-area.
I also ended up rewriting some stuff and moving some stuff out of cider-interaction, so see if you agree with it.

**Comment by bbatsov** [comment]
:+1: Looks good to me. Not sure about the default value for `cider-user-overlays`, but let's merge it as is and see what the users say about it.

**Comment by arrdem** [comment]
:+1: yey more pretty!

**Comment by Malabarba** [comment]
:+1: 

And I'm not sure about the default value either.

**Comment by Malabarba** [comment]
Here's a data point for the default-value discussion. When you get a result of several lines, having it print in both places will completely take up the window.

**Comment by bbatsov** [comment]
@Malabarba Maybe we should just leave the old version as the default and add a note and a screenshot to the README, regarding the overlays. I'm totally fine with making them the default as well, I'm just worried about potential bugs, as this hasn't been tested that extensively yet.

**Comment by Malabarba** [comment]
@bbatsov Yes, I've been using it and uncovering a few corner cases. There'll be a PR related to that soon.
It might be good to turn this off before release (but maybe keep it on until then?).

**Comment by bbatsov** [comment]
You're a mind reader - this is exactly what I've been thinking about. It makes a lot of sense to solicit feedback about the feature right now, so let's leave it on until the release.

**Pull request merged**
