### PR TITLE
Correct typo in comment

### PR DESCRIPTION
**Pull request by johnv02139**
Just fixing a typo in a comment.

-----------------

Before submitting the PR make sure the following things have been done (and denote this
by checking the relevant checkboxes):

- [ ] The commits are consistent with our [contribution guidelines][1]
- [ ] You've added tests (if possible) to cover your change(s)
- [ ] All tests are passing (`make test`)
- [ ] The new code is not generating bytecode or `M-x checkdoc` warnings
- [ ] You've updated the changelog (if adding/changing user-visible functionality)
- [ ] You've updated the readme (if adding/changing user-visible functionality)
- [ ] You've updated the refcard (if you made changes to the commands listed there)

Thanks!

[1]: https://github.com/clojure-emacs/cider/blob/master/.github/CONTRIBUTING.md

### CODE REVIEW

**Comment by bbatsov** [comment]
Thanks!

**Comment by expez** [comment]
Sweet jesus, we now have a commit message ending in a `.` in our git history!

**Comment by bbatsov** [comment]
We don't. I updated the commit prior to merging it. ;-)

**Comment by bbatsov** [comment]
See https://github.com/clojure-emacs/cider/commit/0dd47712588eae6cd057c1c5ad46658d7dec71e0

**Comment by Malabarba** [comment]
:smile:

**Pull request merged**
