### PR TITLE
[Fix #1659] Add fringe indicators for evaluated forms

### PR DESCRIPTION
**Pull request by Malabarba**
Out of all the fringe bitmap options, these 4 are the ones that seem most appropriate.
Not sure which one to use though.
screenshot-2016-04-18--194945-0300

### CODE REVIEW

**Comment by bbatsov** [comment]
I like option 1 and 4 the most.

**Comment by expez** [comment]
Does the face also work as a setting? E.g. if I set the face to `nil` it won't draw anything?

**Comment by Malabarba** [comment]
@expez No. We'll have to make a variable for that.

**Comment by bbatsov** [comment]
I'm guessing we'll have one for evaluations which resulted in an error. An maybe one for evals that produced warnings (not sure about this one).

We should also mention this in the changelog.

**Comment by Malabarba** [comment]
I've only implemented the evaluation indicator for now. I'd like to do the error too eventyually.
There's also a custom option to disable this.

**Comment by vspinu** [comment]
What was the motivation for this? I always start with loading the entire buffer, thus all forms end up having this fringe marker. To me it seems like a useless functionality which also interferes with other packages (#2018). 

I am looking into fixing #2018 but I think for the long run it would be better to entirely remove this.

**Pull request merged**
