### PR TITLE
Update parseedn/parseclj to the latest version

### LINKED ISSUE #3059: Error `(void-function parseclj-alist)` after recent update
## Expected behavior

No errors are reported after performing `cider-clj-jack-in` command.

## Actual behavior

The following error is thrown:

```emacs-lisp
Debugger entered--Lisp error: (void-function parseclj-alist)
  parseclj-alist(:token-type :lparen :form "(" :pos 1)
  apply(parseclj-alist :token-type :lparen :form "(" :pos 1 nil)
  parseclj-lex-token(:lparen "(" 1)
  parseclj-lex-next()
  parseclj-parser(parseedn-reduce-leaf parseedn-reduce-branch ((:tag-readers)))
  parseedn-read(nil)
  parseedn-read-str("(ws180.http.endpoints.v1-ipready-test \"OK\" ws180.h...")
  cljr--maybe-nses-in-bad-state((dict "ast-statuses" "(ws180.http.endpoints.v1-ipready-test \"OK\" ws180.h..." "id" "10" "session" "6e69aaf1-d5ba-4ad8-99e4-dc5a9297cb14" "status" ("done")))
  #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_141>((dict "ast-statuses" "(ws180.http.endpoints.v1-ipready-test \"OK\" ws180.h..." "id" "10" "session" "6e69aaf1-d5ba-4ad8-99e4-dc5a9297cb14" "status" ("done")))
  nrepl--dispatch-response((dict "ast-statuses" "(ws180.http.endpoints.v1-ipready-test \"OK\" ws180.h..." "id" "10" "session" "6e69aaf1-d5ba-4ad8-99e4-dc5a9297cb14" "status" ("done")))
  nrepl-client-filter(#<process nrepl-connection> "d12:ast-statuses5824:(ws180.http.endpoints.v1-ipre...")

```

### CIDER version information

```
;; CIDER 1.2.0snapshot (package: 20210929.1032), nREPL 0.9.0-beta2
;; Clojure 1.10.3, Java 16.0.2
```

### Lein/Boot version

Leiningen 2.9.7 on Java 16.0.2 OpenJDK 64-Bit Server VM

### Emacs version

GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.30, cairo version 1.17.4) of 2021-09-22

### Operating system

Linux 5.14.8-arch1-1 #1 SMP PREEMPT Sun, 26 Sep 2021 19:36:15 +0000 x86_64 GNU/Linux

### PR DESCRIPTION
**Pull request by plexus**
This is a bugfix release, it is important we pull in this one and not 1.0.0 or
1.0.1.

Closes #3059

### CODE REVIEW

**Comment by plexus** [comment]
Seems melpa hadn't picked up the new version yet, re-triggering the build

**Comment by plexus** [comment]
Seems `(map-merge 'alist seqs...)` only works in Emacs 27. Trying again...

**Comment by bbatsov** [comment]
I see in the CI log this:

> [00:04.647]  Emacs version 26 is required (this is version 25.3.1)

It seems that map.el depends on Emacs 26, so probably we'll have to bump our deps across the board, as backporting would be more painful.

**Comment by plexus** [comment]
Dropping 25 would already be great, seems it's ~5 years old at this point? 26 has been out for ~3.5 years.

It still seems `map.el` isn't as capable on 26 as it is on 27, but trying to work around that.

How long does MELPA usually take to pick up a new version? really annoying to have to wait for that...

**Comment by bbatsov** [comment]
> How long does MELPA usually take to pick up a new version? really annoying to have to wait for that...

I think it rebuilds the packages every few hours, but I don't recall the exact details. 

> Dropping 25 would already be great, seems it's ~5 years old at this point? 26 has been out for ~3.5 years.

Yeah, that's true. I think recent versions of RHEL and Debian stable have been shipping Emacs 26, so we should be good.

**Comment by plexus** [comment]
And it's all green :) now that we have windows builds again I could actually see what was going wrong there.

**Comment by bbatsov** [comment]
Nice!

**Comment by gmartsenkov** [comment]
Not sure if it's relevant but i'm having trouble installing cider 🤔 , I'm getting this error:
```
Error (use-package): Failed to install cider: https://melpa.org/packages/parseedn-20210930.542.el: Not found
Error (use-package): Cannot load cider 
```

Running emacs 28.0.50

**Comment by plexus** [comment]
Maybe try refreshing your melpa index? We releases a few versions in quick
succession, and melpa only keeps the most recent.

**Pull request merged**
