### PR TITLE
Restore inhibit-same-window behaviour

### PR DESCRIPTION
**Pull request by cichli**

### CODE REVIEW

**Comment by cichli** [comment]
Sorry, to clarify what was happening here - in async request handlers, the current buffer is the connection buffer, so we should actually be checking if the selected window is equal to the window of the buffer we're popping up (rather than checking if the current buffer is the buffer we're popping up).

@vspinu after using this for a day I now see that using `inhibit-same-window` is clearly better than the default here; sorry for reverting it.

**Comment by vspinu** [comment]
> in async request handlers, the current buffer is the connection buffer, so we should actually be checking if the selected window is equal to the window 

That makes sense, indeed. The change looks ok to me.  Would you please add this clarification inline? So that we don't forget why that window juggling is there.

**Comment by cichli** [comment]
@vpsinu thanks! I've added a note above the `selected-window` check.

**Comment by bbatsov** [comment]
:+1: Looks legit!

**Pull request merged**
