### PR TITLE
Adding cider-nrepl-port-search-paths defcustom

### PR DESCRIPTION
**Pull request by dantheobserver**
This defcustom is useful for cases when you want to connect to a local repl but
are using boot repl spawned from a location that is not a project folder.
The boot process does not display the start directory so we cannot search for
the nrepl-port file from the process. This defcustom allows you to list common
places where you would spawn your boot repl and add that to the search path when
looking for nrepl-port files to show in.

**Replace this placeholder text with a summary of the changes in your PR.
The more detailed you are, the better.**

-----------------

Before submitting the PR make sure the following things have been done (and denote this
by checking the relevant checkboxes):

- [ ] The commits are consistent with our [contribution guidelines][1]
- [ ] You've added tests (if possible) to cover your change(s)
- [x] All tests are passing (`make test`)
- [x] All code passes the linter (`make lint`) which is based on [`elisp-lint`](https://github.com/gonewest818/elisp-lint) and includes
  - [byte-compilation](https://www.gnu.org/software/emacs/manual/html_node/elisp/Byte-Compilation.html), [`checkdoc`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Tips.html), [check-declare](https://www.gnu.org/software/emacs/manual/html_node/elisp/Declaring-Functions.html), packaging metadata, indentation, and trailing whitespace checks.
- [x] You've updated the [changelog][3] (if adding/changing user-visible functionality)
- [x] You've updated the [user manual][4] (if adding/changing user-visible functionality)

Thanks!

*If you're just starting out to hack on CIDER you might find this [section of its
manual][2] extremely useful.*

[1]: https://github.com/clojure-emacs/cider/blob/master/.github/CONTRIBUTING.md
[2]: https://cider.readthedocs.io/en/latest/hacking_on_cider/
[3]: https://github.com/clojure-emacs/cider/blob/master/CHANGELOG.md
[4]: https://github.com/clojure-emacs/cider/tree/master/doc

### CODE REVIEW

**Comment by bbatsov** [comment]
> This defcustom is useful for cases when you want to connect to a local repl but
are using boot repl spawned from a location that is not a project folder.

Wouldn't you have same problem with lein as well? I'm also wondering how people are going to understand what this/make use of it.

**Comment by dantheobserver** [comment]
@bbatsov the lein process has attached to it the directory it was spawned from.  The boot process is very bare.  I'm not familiar with a way to annotate a boot process but if that's possible perhaps that can be part of the instruction and make this obsolete.  I tried adding boot to the lookup but saw that the process itself is fairy bare.  

There is a way to do it, involving capturing the process PID and doing a pwdx <PID>, but I think that would be overkill.  I supposed this may be too.

**Comment by bbatsov** [comment]
That's an interesting point. Frankly, I've never liked the approach of extracting info from `ps`, as obviously that's not exactly portable. Unfortunately I'm short on great alternatives as well. :-(

**Comment by dantheobserver** [comment]
So I slept on it and agree, I think this option is really just for me as I applied it locally. I wanted to propose a non-invasive solution since I can't guarantee how boot or lein (or clj or whatever comes down the line) handles the .nrepl-port file if at all.  I looked into doing something with the boot repl task to output the port to the home folder and check for that by default, but didn't get far.  I'd like to have a one-size-fits-all solution, but I guess I need some more research to do so.

**Comment by bbatsov** [comment]
@dantheobserver Perhaps boot can be updated to display similar info to the one displayed by lein? I assume that's nothing hard.

**Pull request closed without merging**
