### PR TITLE
Bug fixes for 0.10.2

### LINKED ISSUE #1509: ClojureScript buffers not sending cider commands to CLJS REPL
I could have sworn this was working at one point in the development of 0.10.1, but now it's not.

**Steps to reproduce:**

1. Run `lein new figwheel cider-cljs -- --om`.
1. Add `:profiles {:dev {:dependencies [[com.cemerick/piggieback "0.2.1"]
                                  [org.clojure/tools.nrepl "0.2.12"]]}}` to `project.clj`
1. Open `src/cider-cljs/core.cljs` in Emacs.
1. Hit `C-c M-J` in that buffer to run `cider-jack-in-clojurescript`.
1. Once the REPL starts up, hit `C-c C-k` to evaluate the buffer.

**Expected result:**

CIDER evals the buffer in the CLJS REPL.

**Observed result:**

CIDER attempts to eval the buffer in the CLJ REPL and generates an error like `Unable to resolve symbol: enable-console-print!`.

**Versions:**

* Mac OS X 10.11.2
* Emacs (mac-port) 24.5.1
* CIDER 0.10.1
* cider-nrepl 0.10.1
* nrepl 0.2.12
* Java 1.8.0_60
* Clojure 1.7.0
* ClojureScript 1.7.170

It seems to do this with other commands too. `C-c M-n` causes the CLJ REPL to switch to the ClojureScript buffer's namespace, but not the CLJS REPL.

### PR DESCRIPTION
**Pull request by cap10morgan**
This pulls in a commit from master that fixes #1509.

Is there anything else I should put together for a 0.10.2 release?

### CODE REVIEW

**Comment by bbatsov** [comment]
Nothing comes to mind right now, but something might pop up in the next week or so. The last couple of weeks were pretty quiet for cider.

**Comment by cap10morgan** [comment]
@bbatsov Should I backport #1521 onto this branch and then we can do a 0.10.2 release?

**Comment by bbatsov** [comment]
Guess so, although those are small fixes and I'm not sure if they alone warrant a release.

**Comment by cap10morgan** [comment]
@bbatsov Yeah, but #1509 alone is a huge pain for anyone doing CLJS work. I would argue that small releases are just what the 0.10.x branch calls for, and waiting a week or two and only finding a couple bugs to put into a release means that it's getting better! :)

**Comment by bbatsov** [comment]
Fine. I just hate cutting new `cider-nrepl` releases. :-)

**Comment by cap10morgan** [comment]
@bbatsov I'm happy to do the work for you if you give me the steps and the permissions.

Do any fixes or 0.10.x-appropriate changes need to go into `cider-nrepl` first?

**Comment by bbatsov** [comment]
Just prepare the commit bumping all the versions and I'll do the rest. It's not that much work. There are no backend changes, but we need to cut a release to match the versions of the two projects.

**Comment by bbatsov** [comment]
Released. Guess you can update the changelog in `master` now.

**Pull request merged**
