### PR TITLE
Add feature to evaluate list around point

### PR DESCRIPTION
**Pull request by gveres**
This adds a new function cider-eval-list-at-point,  that evaluates a list around point [as in: code delimited by the nearest pair of parens surrounding point]. This comes handy to evaluate a function call while the point is anywhere within the function call.
It's modelled after the eval-sexp-at-point solution, and as such, deals with the "deref @" and other quirks intelligently.

In terms of the implementation, it's built on a thingatpoint built-in feature, so no magic text manipulation is happening. Although the thingatpoint code targets Emacs Lisp, it should work fine with Clojure code too.

Sorry, no tests (yet) - I'd appreciate some help or guidance on what to cover for this.

-----------------

Before submitting the PR make sure the following things have been done (and denote this
by checking the relevant checkboxes):

- [x] The commits are consistent with our [contribution guidelines](../blob/master/.github/CONTRIBUTING.md)
- [ ] You've added tests (if possible) to cover your change(s)
- [ ] All tests are passing (`make test`)
- [ ] All code passes the linter (`make lint`) which is based on [`elisp-lint`](https://github.com/gonewest818/elisp-lint) and includes
  - [byte-compilation](https://www.gnu.org/software/emacs/manual/html_node/elisp/Byte-Compilation.html), [`checkdoc`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Tips.html), [check-declare](https://www.gnu.org/software/emacs/manual/html_node/elisp/Declaring-Functions.html), packaging metadata, indentation, and trailing whitespace checks.
- [ ] You've updated the [changelog](../blob/master/CHANGELOG.md) (if adding/changing user-visible functionality)
- [ ] You've updated the [user manual](../blob/master/doc) (if adding/changing user-visible functionality)

Thanks!

*If you're just starting out to hack on CIDER you might find this [section of its
manual][1] extremely useful.*

[1]: https://docs.cider.mx/cider/contributing/hacking.html

### CODE REVIEW

**Comment by bbatsov** [comment]
Isn't `cider-eval-sexp-at-point` pretty much the same?

**Comment by gveres** [comment]
> Isn't `cider-eval-sexp-at-point` pretty much the same?

No: as I understand, a symbol is also a sexp in the implementation, so if point is on a symbol, that symbol get evaluated, not the surrounding list. list-at-point will expand to include the innermost surrounding paren pair, and sends that whole thing ("compound form"?) to eval.

**Comment by bbatsov** [comment]
Yeah, I think you're right. I use only eval-last-sexp and eval-defun, so my memory on everything else is fuzzy. I'll merge this as is and I'll add a couple of tests myself.

**Comment by gveres** [comment]
Amazing - thanks a lot, @bbatsov!

**Pull request merged**
