### PR TITLE
Improve CIDER's menu-bar menu

### PR DESCRIPTION
**Pull request by Malabarba**
- Thoroughly reorganize it and split it into 3 separate menus;
- Add a 4th menu, that only appears if `cider-mode` isn't active;
- Add custom-written `:help` strings to some items, and automatically add help strings to the rest;
- Add a few commands;
- Grey-out commands that rely on connections while there is no connection.

### CODE REVIEW

**Comment by bbatsov** [comment]
Can you add a couple of screenshots illustrating the changes?

**Comment by Malabarba** [comment]
# What it looks like before you connect (or after you quit).

screenshot-2016-04-11--123922-0300

# What it looks like while you're connected.

screenshot-2016-04-11--123609-0300
screenshot-2016-04-11--123700-0300
screenshot-2016-04-11--123646-0300
screenshot-2016-04-11--123626-0300

**Comment by bbatsov** [comment]
I've just went over the code more closely and the changes look good to me. If you get to doing the screenshots you might add them to the manual (together with some mentions of relevant menus). Lately I've been pouring most of my CIDER time in the manual and I hope to get into some decent shape for Clojure/west.

**Comment by bbatsov** [comment]
Haha, that's what I call perfect timing. :-)

**Comment by Malabarba** [comment]
I added one of the images to the readme. I was afraid that including the others might add too much volume. Feel free to change more of it if you'd like! :)

**Pull request merged**
